// Single source of truth for the parish calendar. Feeds three things from
// one place: the interactive calendar's data file
// (public/js/calendar-events.js, generated by scripts/build.mjs), the
// noscript fallback list on calendar.html ({{EVENTS_NOSCRIPT}}), and the
// Event structured data on calendar.html. Previously the calendar data lived
// only in public/js/calendar-events.js (hand-edited) with a second copy of
// the one-off events hand-mirrored into calendar.html's <noscript> list —
// edit the arrays below and run `npm run build` instead; both generated
// outputs follow automatically.

// Special services, concerts and one-off events. Recurring weekly community
// activities go in RECURRING_SERIES below instead.
export const ONE_OFF_EVENTS = [
  { date: '2026-06-07', time: '18:00', title: 'Junior Praise', location: 'Old Radnor' },
  { date: '2026-06-12', time: '19:00', title: 'Organ Concert: Roger Judd (Diocesan Organ Advisor)', location: "St Mary's, Kington" },
  { date: '2026-06-14', time: '15:00', title: 'Wild Church', location: 'Kington' },
  { date: '2026-06-21', time: '14:00', title: 'Pilgrimage and tea', location: "St Stephen's, Old Radnor" },
  { date: '2026-07-03', time: '19:00', title: "Concert: Hilary Norris (organ) and Joris Boon ('cello)", location: "St Mary's, Kington" },
  { date: '2026-07-04', time: '10:30', title: "Phillippa's Ordination", location: 'Hereford Cathedral' },
  { date: '2026-07-19', time: '11:00', title: 'Picnic Praise', location: "St Mary's, Kington" },
  { date: '2026-07-19', time: '14:00', title: 'Pilgrimage and tea', location: "St Peter's, Titley" },
  { date: '2026-07-28', time: '10:30', title: "Summer Family Fun at St Mary's", location: "St Mary's, Kington" },
  { date: '2026-08-01', time: '16:20', title: 'Visiting Ringers (Holmer Tower outing)', location: "St Mary's, Kington" },
  { date: '2026-08-09', time: '16:00', title: 'Choral Evensong: Derby Singers, with a short recital', location: "St Mary's, Kington" },
  { date: '2026-08-11', time: '10:30', title: "Summer Family Fun at St Mary's", location: "St Mary's, Kington" },
  { date: '2026-08-16', time: '14:00', title: 'Pilgrimage and tea', location: "St Thomas à Becket, Huntington" },
  { date: '2026-08-25', time: '10:30', title: "Summer Family Fun at St Mary's", location: "St Mary's, Kington" },
  { date: '2026-08-30', time: '16:00', title: 'Choral Evensong sung by the Church House Singers', location: "St Mary's, Kington" },
  // Sunday services, September-November 2026: Holy Communion every Sunday
  // except the third Sunday of the month, which is Morning Praise. Only
  // covers Sep-Nov for now — see CLAUDE.md.
  { date: '2026-09-06', time: '10:00', title: 'Holy Communion', location: "St Mary's, Kington" },
  { date: '2026-09-12', time: '19:00', title: 'Organ Recital: Ewan Murray', location: "St Mary's, Kington" },
  { date: '2026-09-13', time: '10:00', title: 'Holy Communion', location: "St Mary's, Kington" },
  { date: '2026-09-16', time: '15:30', title: 'Lego Club', location: "St Mary's, Kington" },
  { date: '2026-09-20', time: '10:00', title: 'Morning Praise', location: "St Mary's, Kington" },
  { date: '2026-09-20', time: '13:45', title: "Kington Pilgrim Path Walk from St Mary's", location: "St Mary's, Kington" },
  { date: '2026-09-20', time: '14:00', title: 'Pilgrimage and tea', location: "St Mary's, Kinnerton" },
  { date: '2026-09-27', time: '10:00', title: 'Holy Communion', location: "St Mary's, Kington" },
  { date: '2026-10-04', time: '10:00', title: 'Harvest Festival', location: "St Mary's, Kington" },
  { date: '2026-10-04', time: '18:00', title: 'Praise & Prayer in the Evening (PPE)', location: "St Mary's, Kington" },
  { date: '2026-10-11', time: '10:00', title: 'Holy Communion', location: "St Mary's, Kington" },
  { date: '2026-10-16', time: '19:00', title: "'Jug of Punch' October Concert", location: "St Mary's, Kington" },
  { date: '2026-10-18', time: '10:00', title: 'Morning Praise', location: "St Mary's, Kington" },
  { date: '2026-10-21', time: '15:30', title: 'Lego Club', location: "St Mary's, Kington" },
  { date: '2026-10-25', time: '10:00', title: 'Holy Communion', location: "St Mary's, Kington" },
  { date: '2026-10-28', time: '10:20', title: 'Visiting Ringers', location: "St Mary's, Kington" },
  { date: '2026-11-01', time: '10:00', title: 'Holy Communion', location: "St Mary's, Kington" },
  { date: '2026-11-01', time: '18:00', title: 'Praise & Prayer in the Evening (PPE)', location: "St Mary's, Kington" },
  { date: '2026-11-08', time: '10:00', title: 'Holy Communion', location: "St Mary's, Kington" },
  { date: '2026-11-15', time: '10:00', title: 'Morning Praise', location: "St Mary's, Kington" },
  { date: '2026-11-15', time: '15:30', title: 'Recital by the Titley Philharmonic Orchestra (Bach Double Violin Concerto and Handel Organ Concerto)', location: "St Mary's, Kington" },
  { date: '2026-11-18', time: '15:30', title: 'Lego Club', location: "St Mary's, Kington" },
  { date: '2026-11-22', time: '10:00', title: 'Holy Communion', location: "St Mary's, Kington" },
  { date: '2026-11-29', time: '10:00', title: 'Holy Communion', location: "St Mary's, Kington" },
  { date: '2026-12-06', time: '18:00', title: 'Praise & Prayer in the Evening (PPE)', location: "St Mary's, Kington" },
  { date: '2026-12-09', time: '15:30', title: 'Lego Club', location: "St Mary's, Kington" },
  { date: '2026-12-11', time: '18:30', title: 'Carols at the Oxford', location: '' },
];

// Recurring weekly activities. Each series expands into one entry per
// occurrence between `from` and `until` (inclusive), on the given weekday
// (1 = Monday ... 7 = Sunday, ISO-style), skipping any dates listed in
// `except` (bank holidays, term breaks, etc.).
//
// To carry a series into next year, just extend `until`. To skip a holiday,
// add its date to `except` — no more hand-typing one row per week.
export const RECURRING_SERIES = [
  // St Mary's Parish Hall — Mondays 12:15-13:00 & Fridays 10:00-11:00 (see
  // the homepage noticeboard).
  { title: 'Kington Zero Waste', location: "St Mary's Parish Hall", weekday: 1, time: '12:15', from: '2026-08-31', until: '2026-12-31' },
  { title: 'Kington Zero Waste', location: "St Mary's Parish Hall", weekday: 5, time: '10:00', from: '2026-09-04', until: '2026-12-31', except: ['2026-12-25'] },
  // Term-time only (per the homepage noticeboard) — skip Herefordshire
  // school holidays. Update `except` once next term's dates are known.
  { title: 'Stay and Play', location: "St Mary's Parish Hall", weekday: 2, time: '09:15', from: '2026-09-01', until: '2026-12-31', except: ['2026-10-27', '2026-12-22', '2026-12-29'] },
  // Not term-time restricted — runs straight through, including the school
  // holidays Stay and Play skips.
  { title: 'Marches Voices Choir', location: 'Kington Parish Hall', weekday: 2, time: '14:00', from: '2026-09-01', until: '2026-12-31' },
];

// Known venues' addresses, for Event structured data's `location` — same
// localities as the Church entries in the our-churches JSON-LD
// (src/pages.config.mjs). Matched against an event's free-text `location`
// by substring, so "St Mary's, Kington" and plain "Kington" both resolve.
// Anything that doesn't match (Hereford Cathedral, The Oxford, blank) still
// gets a valid Place — just without a postal address.
const CHURCH_LOCALITIES = [
  { match: 'kington', locality: 'Kington' },
  { match: 'titley', locality: 'Titley' },
  { match: 'old radnor', locality: 'Old Radnor' },
  { match: 'kinnerton', locality: 'Kinnerton' },
  { match: 'huntington', locality: 'Huntington' },
];

export function placeFor(location) {
  // No location given (e.g. "Carols at the Oxford", which names the venue in
  // its title instead) — a real address would be a guess, so don't attach
  // one just because the generic fallback name happens to contain "Kington".
  if (!location) return { '@type': 'Place', name: 'Kington Parishes' };
  const found = CHURCH_LOCALITIES.find((c) => location.toLowerCase().includes(c.match));
  if (!found) return { '@type': 'Place', name: location };
  return {
    '@type': 'Place',
    name: location,
    address: { '@type': 'PostalAddress', addressLocality: found.locality, addressCountry: 'GB' },
  };
}

function pad(n) { return n < 10 ? '0' + n : '' + n; }
function dateStr(d) { return d.getFullYear() + '-' + pad(d.getMonth() + 1) + '-' + pad(d.getDate()); }

function expandSeries(series) {
  const out = [];
  const fromParts = series.from.split('-').map(Number);
  const untilParts = series.until.split('-').map(Number);
  const d = new Date(fromParts[0], fromParts[1] - 1, fromParts[2]);
  const until = new Date(untilParts[0], untilParts[1] - 1, untilParts[2]);
  // JS Date#getDay(): 0 = Sunday ... 6 = Saturday. Convert our ISO weekday
  // (1 = Monday ... 7 = Sunday) to that scale.
  const jsWeekday = series.weekday % 7;
  while (d.getDay() !== jsWeekday) d.setDate(d.getDate() + 1);
  const except = series.except || [];
  while (d <= until) {
    const ds = dateStr(d);
    if (!except.includes(ds)) {
      out.push({ date: ds, time: series.time, title: series.title, location: series.location });
    }
    d.setDate(d.getDate() + 7);
  }
  return out;
}

// The full calendar: every one-off plus every recurring occurrence,
// sorted chronologically. This is what public/js/calendar-events.js gets
// generated from, and what calendar.html's noscript list and Event
// structured data both filter down from.
export function expandEvents() {
  const recurring = RECURRING_SERIES.flatMap(expandSeries);
  return [...ONE_OFF_EVENTS, ...recurring].sort((a, b) =>
    a.date === b.date ? a.time.localeCompare(b.time) : a.date.localeCompare(b.date));
}

// "18:00" -> "6:00pm", "09:15" -> "9:15am" — matches the display format
// already used across the site's own event listings.
export function formatTime12h(time24) {
  const [h, m] = time24.split(':').map(Number);
  const period = h < 12 ? 'am' : 'pm';
  const h12 = h % 12 === 0 ? 12 : h % 12;
  return `${h12}:${pad(m)}${period}`;
}

const DAY_NAMES = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
const MONTH_NAMES = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

// "2026-06-07" -> "Sun 7 June" — matches the display format already used
// across the site's own event listings.
export function formatEventDate(dateStr) {
  const [y, m, d] = dateStr.split('-').map(Number);
  const date = new Date(y, m - 1, d);
  return `${DAY_NAMES[date.getDay()]} ${d} ${MONTH_NAMES[m - 1]}`;
}
