// Single source of truth for the main nav, the footer's shorter "Explore"
// list, and each page's <head> metadata. Edit this file (and
// src/pages/*.html for content) — public/*.html is generated by
// scripts/build.mjs and should not be hand-edited.
//
// Every page carries robots: 'noindex, nofollow' — this is a proof-of-concept
// build showcasing the MediaWright pipeline, not the parishes' real
// production website, and it must never be confused with (or outrank) the
// genuine site in search results.

// The header's primary nav — every page except 404 shows this.
// "Home" isn't a link here: the brand link in the header already goes to
// index.html, so a second link to the same place would be redundant — that
// slot is used for Walkers instead.
export const NAV = [
  { href: 'our-churches.html', label: 'Our Churches' },
  { href: 'our-people.html', label: 'Our People' },
  { href: 'walkers.html', label: 'Walkers' },
  { href: 'services.html', label: 'Services &amp; Events' },
  { href: 'parish-news.html', label: 'Parish News' },
  { href: 'life-events.html', label: 'Life Events' },
  { href: 'get-involved.html', label: 'Get Involved' },
  { href: 'calendar.html', label: 'Calendar' },
  { href: 'contact.html', label: 'Contact' },
];

// The footer's shorter "Explore" list — deliberately a different set than
// NAV (it includes Safeguarding, which isn't in the primary nav, and
// excludes Life Events/Get Involved/Contact).
export const FOOTER_NAV = [
  { href: 'our-churches.html', label: 'Our Churches' },
  { href: 'services.html', label: 'Services &amp; Events' },
  { href: 'parish-news-archive.html', label: 'Parish News' },
  { href: 'safeguarding.html', label: 'Safeguarding' },
  { href: 'https://www.youtube.com/@KingtonStMaryLive', label: 'Our YouTube Channel' },
  { href: 'https://www.facebook.com/kingtonparishes', label: 'Our Facebook Community' },
];

export const PAGES = [
  {
    slug: 'index',
    title: 'Kington Parishes — Five churches on the Herefordshire/Powys border',
    description: "Kington Parishes: St Mary's Kington, St Peter's Titley, St Stephen's Old Radnor, St Mary's Kinnerton and St Thomas à Becket Huntington. Services, news, and community events.",
    active: 'index.html',
    header: true,
    robots: 'noindex, nofollow',
  },
  {
    slug: 'our-churches',
    title: 'Our Churches — Kington Parishes',
    description: "The five churches of Kington Parishes: St Mary's Kington, St Peter's Titley, St Stephen's Old Radnor, St Mary's Kinnerton, and St Thomas à Becket Huntington.",
    active: 'our-churches.html',
    header: true,
    robots: 'noindex, nofollow',
  },
  {
    slug: 'our-people',
    title: 'Our People — Kington Parishes',
    description: 'Meet the clergy and the volunteer wardens and officers who run our parishes: Revd Sally Welch, Revd Phillippa Wright, and the churchwardens, safeguarding, health & safety and treasury team at St Mary\'s, Kington.',
    active: 'our-people.html',
    header: true,
    robots: 'noindex, nofollow',
  },
  {
    slug: 'walkers',
    title: 'Walkers Welcome — Kington Parishes',
    description: "Walking near Kington: our own way-marked Pilgrim Paths, the Offa's Dyke Path, and other local routes — plus an open invitation to stop at St Mary's, Kington for tea, biscuits and the facilities.",
    active: 'walkers.html',
    header: true,
    robots: 'noindex, nofollow',
  },
  {
    slug: 'services',
    title: 'Services &amp; Events — Kington Parishes',
    description: 'Worship patterns across our five churches, live-streamed services, and our shared calendar.',
    active: 'services.html',
    header: true,
    robots: 'noindex, nofollow',
  },
  {
    slug: 'parish-news',
    title: 'Parish News — Kington Parishes',
    description: 'The family magazine of the Churches of Kington, Huntington, Old Radnor, Kinnerton and Titley.',
    active: 'parish-news.html',
    header: true,
    robots: 'noindex, nofollow',
  },
  {
    slug: 'parish-news-archive',
    title: 'Parish News Archive — Kington Parishes',
    description: 'Back issues of Parish News, the monthly magazine of Kington, Huntington, Old Radnor, Kinnerton and Titley — download any issue as a PDF.',
    // Reachable from the Parish News page and the footer's Explore list,
    // not from the primary nav — same pattern as Safeguarding.
    active: null,
    header: true,
    robots: 'noindex, nofollow',
  },
  {
    slug: 'life-events',
    title: 'Life Events — Kington Parishes',
    description: 'Baptisms, weddings, funerals and remembrance services across the Kington Parishes.',
    active: 'life-events.html',
    header: true,
    robots: 'noindex, nofollow',
  },
  {
    slug: 'get-involved',
    title: 'Get Involved — Kington Parishes',
    description: 'Hire the Parish Hall, join the church fete, support our fundraising, and find out what drives our mission.',
    active: 'get-involved.html',
    header: true,
    robots: 'noindex, nofollow',
  },
  {
    slug: 'calendar',
    title: 'Calendar — Kington Parishes',
    description: 'Special services, concerts and one-off events across our five churches, month by month.',
    active: 'calendar.html',
    header: true,
    robots: 'noindex, nofollow',
  },
  {
    slug: 'contact',
    title: 'Contact — Kington Parishes',
    description: 'Get in touch with Kington Parishes — office, vicar, and hall booking contacts.',
    active: 'contact.html',
    header: true,
    robots: 'noindex, nofollow',
  },
  {
    slug: 'safeguarding',
    title: 'Safeguarding — Kington Parishes',
    description: 'Safeguarding contacts and national helplines for Kington Parishes.',
    active: null,
    header: true,
    // The safeguarding page doesn't need to link to itself.
    safeguardStrip: false,
    robots: 'noindex, nofollow',
  },
  {
    slug: 'updates',
    title: 'Site Updates — Kington Parishes',
    description: 'Internal build changelog for this site — not linked from anywhere on the site.',
    active: null,
    header: true,
    // Not pastoral content — skip the safeguard-strip banner, same
    // reasoning as the 404 page.
    safeguardStrip: false,
    robots: 'noindex, nofollow',
  },
  {
    slug: '404',
    title: 'Page not found — Kington Parishes',
    description: "This page couldn't be found. Find your way back to Kington Parishes' home page.",
    active: null,
    header: false,
    // Footer stays (build number, mediawright credit, contact details) —
    // only the header nav and safeguard-strip banner are dropped, since
    // this page isn't a nav destination.
    safeguardStrip: false,
    canonical: false,
    robots: 'noindex, nofollow',
  },
];
