// Single source of truth for the main nav, the footer's shorter "Explore"
// list, and each page's <head> metadata. Edit this file (and
// src/pages/*.html for content) — public/*.html is generated by
// scripts/build.mjs and should not be hand-edited.

// The header's primary nav — every page except 404 shows this.
export const NAV = [
  { href: 'index.html', label: 'Home' },
  { href: 'our-churches.html', label: 'Our Churches' },
  { href: 'services.html', label: 'Services &amp; Events' },
  { href: 'parish-news.html', label: 'Parish News' },
  { href: 'life-events.html', label: 'Life Events' },
  { href: 'get-involved.html', label: 'Get Involved' },
  { href: 'contact.html', label: 'Contact' },
];

// The footer's shorter "Explore" list — deliberately a different set than
// NAV (it includes Safeguarding, which isn't in the primary nav, and
// excludes Life Events/Get Involved/Contact).
export const FOOTER_NAV = [
  { href: 'our-churches.html', label: 'Our Churches' },
  { href: 'services.html', label: 'Services &amp; Events' },
  { href: 'parish-news.html', label: 'Parish News' },
  { href: 'safeguarding.html', label: 'Safeguarding' },
];

export const PAGES = [
  {
    slug: 'index',
    title: 'Kington Parishes — Five churches on the Herefordshire/Powys border',
    description: "Kington Parishes: St Mary's Kington, St Peter's Titley, St Stephen's Old Radnor, St Mary's Kinnerton and St Thomas à Becket Huntington. Services, news, and community events.",
    active: 'index.html',
    header: true,
  },
  {
    slug: 'our-churches',
    title: 'Our Churches — Kington Parishes',
    description: "The five churches of Kington Parishes: St Mary's Kington, St Peter's Titley, St Stephen's Old Radnor, St Mary's Kinnerton, and St Thomas à Becket Huntington.",
    active: 'our-churches.html',
    header: true,
  },
  {
    slug: 'services',
    title: 'Services &amp; Events — Kington Parishes',
    description: 'Worship patterns across our five churches, live-streamed services, and our shared calendar.',
    active: 'services.html',
    header: true,
  },
  {
    slug: 'parish-news',
    title: 'Parish News — Kington Parishes',
    description: 'The family magazine of the Churches of Kington, Huntington, Old Radnor, Kinnerton and Titley.',
    active: 'parish-news.html',
    header: true,
  },
  {
    slug: 'life-events',
    title: 'Life Events — Kington Parishes',
    description: 'Baptisms, weddings, funerals and remembrance services across the Kington Parishes.',
    active: 'life-events.html',
    header: true,
  },
  {
    slug: 'get-involved',
    title: 'Get Involved — Kington Parishes',
    description: 'Hire the Parish Hall, join the church fete, support our fundraising, and find out what drives our mission.',
    active: 'get-involved.html',
    header: true,
  },
  {
    slug: 'contact',
    title: 'Contact — Kington Parishes',
    description: 'Get in touch with Kington Parishes — office, vicar, and hall booking contacts.',
    active: 'contact.html',
    header: true,
  },
  {
    slug: 'safeguarding',
    title: 'Safeguarding — Kington Parishes',
    description: 'Safeguarding contacts and national helplines for Kington Parishes.',
    active: null,
    header: true,
    // The safeguarding page doesn't need to link to itself.
    safeguardStrip: false,
  },
  {
    slug: '404',
    title: 'Page not found — Kington Parishes',
    description: "This page couldn't be found. Find your way back to Kington Parishes' home page.",
    active: null,
    header: false,
    // Footer stays (build number, mediawright credit, contact details) —
    // only the header nav and safeguard-strip banner are dropped, since
    // this page isn't a nav destination.
    safeguardStrip: false,
    canonical: false,
    robots: 'noindex',
  },
];
