// Single source of truth for the main nav, the footer's shorter "Explore"
// list, and each page's <head> metadata. Edit this file (and
// src/pages/*.html for content) — public/*.html is generated by
// scripts/build.mjs and should not be hand-edited.
//
// Only `404` and `updates` set robots: 'noindex, nofollow' — a page not
// meant to be a search result, and the internal build changelog,
// respectively. Every real page has no `robots` field at all, which is what
// actually keeps the tag off it (scripts/build.mjs only writes the meta tag
// `if (page.robots)`) — this used to be the reverse (noindex everywhere,
// while this was a proof-of-concept build) until go-live on 6 September 2026.

// The header's primary nav — every page except 404 shows this.
// "Home" isn't a link here: the brand link in the header already goes to
// index.html, so a second link to the same place would be redundant — that
// slot is used for Walkers instead.
export const NAV = [
  { href: 'our-churches.html', label: 'Our Churches' },
  { href: 'our-people.html', label: 'Our People' },
  { href: 'services.html', label: 'Services &amp; Events' },
  { href: 'parish-news.html', label: 'Parish Magazine' },
  { href: 'newsletter.html', label: 'InSpire' },
  { href: 'blog.html', label: 'Blog' },
  { href: 'life-events.html', label: 'Life Events' },
  { href: 'get-involved.html', label: 'Get Involved' },
  { href: 'resources.html', label: 'Resources' },
  { href: 'parish-hall.html', label: 'Parish Hall' },
  { href: 'calendar.html', label: 'Calendar' },
  { href: 'walkers.html', label: 'Walkers' },
  { href: 'contact.html', label: 'Contact' },
];

// The footer's shorter "Explore" list — deliberately a different set than
// NAV (it includes Safeguarding, which isn't in the primary nav, and
// excludes Life Events/Get Involved/Contact).
export const FOOTER_NAV = [
  { href: 'our-churches.html', label: 'Our Churches' },
  { href: 'services.html', label: 'Services &amp; Events' },
  { href: 'parish-news-archive.html', label: 'Parish Magazine' },
  { href: 'newsletter-archive.html', label: 'InSpire Newsletter' },
  { href: 'safeguarding.html', label: 'Safeguarding' },
  { href: 'privacy-policy.html', label: 'Privacy Policy' },
  { href: 'https://www.youtube.com/@KingtonStMaryLive', label: 'Our YouTube Channel' },
  { href: 'https://www.facebook.com/kingtonparishes', label: 'Our Facebook Community' },
];

export const PAGES = [
  {
    slug: 'index',
    title: 'Kington Parishes — Five churches on the Herefordshire/Powys border',
    description: "Kington Parishes: St Mary's Kington, St Peter's Titley, St Stephen's Old Radnor, St Mary's Kinnerton and St Thomas à Becket Huntington. Services, news, and community events.",
    active: 'index.html',
    header: true,
    // The homepage carries its own full safeguarding section (#safeguarding)
    // now, which already links to safeguarding.html — the small strip above
    // the footer would just repeat that on the same page.
    safeguardStrip: false,
    structuredData: {
      '@context': 'https://schema.org',
      '@type': 'Organization',
      name: 'Kington Parishes',
      url: 'https://www.kingtonparishes.org.uk/index.html',
      logo: 'https://www.kingtonparishes.org.uk/img/favicon.svg',
      email: 'vicar@kingtonparishes.org.uk',
      telephone: '+447974439630',
      // Matches SITE in src/site.config.mjs — kept as a separate literal
      // here since structuredData objects in this file are hand-authored,
      // not token-substituted (see the file-level comment above).
      address: {
        '@type': 'PostalAddress',
        streetAddress: 'The Vicarage, Church Road',
        addressLocality: 'Kington',
        addressRegion: 'Herefordshire',
        postalCode: 'HR5 3AG',
        addressCountry: 'GB',
      },
      sameAs: [
        'https://www.youtube.com/@KingtonStMaryLive',
        'https://www.facebook.com/kingtonparishes',
      ],
    },
  },
  {
    slug: 'our-churches',
    title: 'Our Churches — Kington Parishes',
    description: "The five churches of Kington Parishes: St Mary's Kington, St Peter's Titley, St Stephen's Old Radnor, St Mary's Kinnerton, and St Thomas à Becket Huntington.",
    active: 'our-churches.html',
    header: true,
    // One Church entry per parish. Deliberately no `address.addressRegion`
    // (Kington/Titley/Huntington read as Herefordshire, England;
    // Old Radnor/Kinnerton as Powys, Wales, but that's not confirmed against
    // an official source here). `geo` and `hasMap` come from each church's
    // what3words location (see the links on the page itself).
    structuredData: {
      '@context': 'https://schema.org',
      '@graph': [
        {
          '@type': 'Church',
          name: "St Mary the Virgin, Kington",
          url: 'https://www.kingtonparishes.org.uk/our-churches.html#kington',
          image: 'https://www.kingtonparishes.org.uk/img/our-churches/kington.webp',
          address: { '@type': 'PostalAddress', addressLocality: 'Kington', addressCountry: 'GB' },
          geo: { '@type': 'GeoCoordinates', latitude: 52.2045407, longitude: -3.0384017 },
          hasMap: 'https://what3words.com/gripes.remark.dimension',
          telephone: '+447974439630',
          email: 'vicar@kingtonparishes.org.uk',
          sameAs: [
            'https://en.wikipedia.org/wiki/Church_of_St_Mary,_Kington',
            'https://historicengland.org.uk/listing/the-list/list-entry/1208031',
          ],
        },
        {
          '@type': 'Church',
          name: "St Peter's, Titley",
          url: 'https://www.kingtonparishes.org.uk/our-churches.html#titley',
          image: 'https://www.kingtonparishes.org.uk/img/our-churches/titley.webp',
          address: { '@type': 'PostalAddress', addressLocality: 'Titley', addressCountry: 'GB' },
          geo: { '@type': 'GeoCoordinates', latitude: 52.2357368, longitude: -2.9806390 },
          hasMap: 'https://what3words.com/wooden.hence.thankful',
          telephone: '+447974439630',
          email: 'vicar@kingtonparishes.org.uk',
          sameAs: [
            'https://en.wikipedia.org/wiki/Titley_Priory',
            'https://historicengland.org.uk/listing/the-list/list-entry/1081465',
          ],
        },
        {
          '@type': 'Church',
          name: "St Stephen's, Old Radnor",
          url: 'https://www.kingtonparishes.org.uk/our-churches.html#old-radnor',
          image: 'https://www.kingtonparishes.org.uk/img/our-churches/old-radnor.webp',
          address: { '@type': 'PostalAddress', addressLocality: 'Old Radnor', addressCountry: 'GB' },
          geo: { '@type': 'GeoCoordinates', latitude: 52.2249297, longitude: -3.0996140 },
          hasMap: 'https://what3words.com/tolerable.shifting.roosters',
          telephone: '+447974439630',
          email: 'vicar@kingtonparishes.org.uk',
          sameAs: [
            'https://en.wikipedia.org/wiki/St_Stephen%27s_Church,_Old_Radnor',
            'https://coflein.gov.uk/en/site/306985',
          ],
        },
        {
          '@type': 'Church',
          name: "St Mary's, Kinnerton",
          url: 'https://www.kingtonparishes.org.uk/our-churches.html#kinnerton',
          image: 'https://www.kingtonparishes.org.uk/img/our-churches/kinnerton.webp',
          address: { '@type': 'PostalAddress', addressLocality: 'Kinnerton', addressCountry: 'GB' },
          geo: { '@type': 'GeoCoordinates', latitude: 52.2612662, longitude: -3.1088144 },
          hasMap: 'https://what3words.com/active.seducing.revolting',
          telephone: '+447974439630',
          email: 'vicar@kingtonparishes.org.uk',
        },
        {
          '@type': 'Church',
          name: 'St Thomas à Becket, Huntington',
          url: 'https://www.kingtonparishes.org.uk/our-churches.html#huntington',
          image: 'https://www.kingtonparishes.org.uk/img/our-churches/huntington.webp',
          address: { '@type': 'PostalAddress', addressLocality: 'Huntington', addressCountry: 'GB' },
          geo: { '@type': 'GeoCoordinates', latitude: 52.1735393, longitude: -3.0989438 },
          hasMap: 'https://what3words.com/handicaps.messy.ranted',
          telephone: '+447974439630',
          email: 'vicar@kingtonparishes.org.uk',
          sameAs: ['https://historicengland.org.uk/listing/the-list/list-entry/1349556'],
        },
      ],
    },
  },
  // One portal page per church, linked from each church's "Visit the ..."
  // page →" link on Our Churches. Not in the primary nav — reachable only
  // from there, same pattern as Donate/Parish News Archive. Each currently
  // duplicates that church's descriptive text/photo/links from Our Churches
  // by hand (see CLAUDE.md's "Data kept in sync by hand"); only the People
  // cards on church-kington are DRY, via src/people.config.mjs.
  //
  // church-kington-history is a further deep-dive page, reachable only via
  // a "Read the full History & Architecture guide →" link inside
  // church-kington's own History & architecture section — not in the
  // primary nav, and not itself a portal page.
  {
    slug: 'church-kington',
    title: "St Mary the Virgin, Kington — Kington Parishes",
    description: "St Mary the Virgin, Kington: service times, how to give, and the people who lead and serve this church.",
    active: null,
    header: true,
    image: '/img/our-churches/kington.webp',
  },
  {
    slug: 'church-kington-history',
    title: "History &amp; Architecture — St Mary the Virgin, Kington — Kington Parishes",
    description: "The full history and architecture of St Mary the Virgin, Kington: the Norman tower, the Vaughan effigies, the bells, organ, stained glass, and lychgate.",
    active: null,
    header: true,
    image: '/img/our-churches/kington.webp',
  },
  {
    slug: 'church-titley',
    title: "St Peter's, Titley — Kington Parishes",
    description: "St Peter's, Titley: service times, how to give, and how to find this church.",
    active: null,
    header: true,
    image: '/img/our-churches/titley.webp',
  },
  {
    slug: 'church-old-radnor',
    title: "St Stephen's, Old Radnor — Kington Parishes",
    description: "St Stephen's, Old Radnor: service times, how to give, and how to find this church.",
    active: null,
    header: true,
    image: '/img/our-churches/old-radnor.webp',
  },
  {
    slug: 'church-kinnerton',
    title: "St Mary's, Kinnerton — Kington Parishes",
    description: "St Mary's, Kinnerton: service times, how to give, and how to find this church.",
    active: null,
    header: true,
    image: '/img/our-churches/kinnerton.webp',
  },
  {
    slug: 'church-huntington',
    title: 'St Thomas à Becket, Huntington — Kington Parishes',
    description: 'St Thomas à Becket, Huntington: service times, how to give, and how to find this church.',
    active: null,
    header: true,
    image: '/img/our-churches/huntington.webp',
  },
  {
    slug: 'our-people',
    title: 'Our People — Kington Parishes',
    description: 'Meet the clergy and the volunteer wardens and officers who run our five churches: Revd Sally Welch, Revd Phillippa Wright, and the churchwardens, secretaries, organists and other officers across Kington, Titley, Old Radnor, Kinnerton and Huntington.',
    active: 'our-people.html',
    header: true,
  },
  {
    slug: 'walkers',
    title: 'Walkers Welcome — Kington Parishes',
    description: "Walking near Kington: our own way-marked Pilgrim Paths, the Offa's Dyke Path, and other local routes — plus an open invitation to stop at St Mary's, Kington for tea, biscuits and the facilities.",
    active: 'walkers.html',
    header: true,
  },
  {
    slug: 'services',
    title: 'Services &amp; Events — Kington Parishes',
    description: 'Worship patterns across our five churches, live-streamed services, and our shared calendar.',
    active: 'services.html',
    header: true,
  },
  {
    slug: 'parish-news',
    title: 'Parish News — Kington Parishes',
    description: 'The family magazine of the Churches of Kington, Huntington, Old Radnor, Kinnerton and Titley.',
    active: 'parish-news.html',
    header: true,
    image: '/img/parish-news/parish-news-2026-09.jpg',
    // Describes the latest issue — update alongside the "Latest issue" card
    // in src/pages/parish-news.html when a new issue is published.
    structuredData: {
      '@context': 'https://schema.org',
      '@type': 'CreativeWork',
      name: 'Parish News — September 2026',
      url: 'https://www.kingtonparishes.org.uk/parish-news/parish-news-2026-09.pdf',
      encodingFormat: 'application/pdf',
      thumbnailUrl: 'https://www.kingtonparishes.org.uk/img/parish-news/parish-news-2026-09.jpg',
      isPartOf: {
        '@type': 'CreativeWorkSeries',
        name: 'Parish News',
        publisher: { '@type': 'Organization', name: 'Kington Parishes' },
      },
    },
  },
  {
    slug: 'parish-news-archive',
    title: 'Parish News Archive — Kington Parishes',
    description: 'Back issues of Parish News, the monthly magazine of Kington, Huntington, Old Radnor, Kinnerton and Titley — download any issue as a PDF.',
    // Reachable from the Parish News page and the footer's Explore list,
    // not from the primary nav — same pattern as Safeguarding.
    active: null,
    header: true,
    image: '/img/parish-news/parish-news-2026-09.jpg',
  },
  {
    slug: 'newsletter',
    title: 'InSpire Newsletter — Kington Parishes',
    description: 'Sign up for the InSpire Newsletter — news, services and events from across the Kington Parishes, straight to your inbox.',
    active: 'newsletter.html',
    header: true,
  },
  {
    slug: 'newsletter-2026-09',
    title: 'September 2026 — InSpire Newsletter — Kington Parishes',
    description: "25 years of ministry for Revd Sally Welch, Revd Phillippa Wright's ordination as priest, a Treasurer vacancy at St Mary's, and September's Wild Church cancelled.",
    // Reachable from the newsletter page's "Recent issues" list (and later
    // the newsletter archive) via src/newsletter.config.mjs — not the
    // primary nav or the footer, same as every other newsletter issue page.
    active: null,
    header: true,
  },
  {
    slug: 'newsletter-archive',
    title: 'InSpire Newsletter Archive — Kington Parishes',
    description: 'Past issues of the InSpire Newsletter, more than six months old — free to read online.',
    // Reachable from the newsletter page ("Browse the full archive"), not
    // the primary nav or the footer — same pattern as Parish News Archive.
    active: null,
    header: true,
  },
  {
    slug: 'privacy-policy',
    title: 'Privacy Policy — Kington Parishes',
    description: 'How Kington Parishes handles the personal details you give us when signing up for the InSpire Newsletter.',
    // Reachable from the newsletter signup form's consent text and the
    // footer's Explore list, not the primary nav — same pattern as
    // Safeguarding.
    active: null,
    header: true,
  },
  {
    slug: 'blog',
    title: 'Blog — Kington Parishes',
    description: 'Appeals, updates and announcements from across the Kington Parishes — newest post first.',
    active: 'blog.html',
    header: true,
    // One BlogPosting per post — hand-authored, matching the pattern of the
    // Church entries above. Add a matching entry here when a new post is
    // added to src/pages/blog.html (the anchor id in `url` comes from that
    // heading's own text via slugify — see scripts/build-search-index.mjs).
    structuredData: {
      '@context': 'https://schema.org',
      '@type': 'Blog',
      name: 'Kington Parishes Blog',
      url: 'https://www.kingtonparishes.org.uk/blog.html',
      publisher: { '@type': 'Organization', name: 'Kington Parishes' },
      blogPost: [
        {
          '@type': 'BlogPosting',
          headline: "We're recruiting a Treasurer for St Mary's, Kington",
          url: 'https://www.kingtonparishes.org.uk/blog.html#we-re-recruiting-a-treasurer-for-st-mary-s-kington',
          datePublished: '2026-09-02',
          author: { '@type': 'Person', name: 'Greg Wright' },
        },
      ],
    },
  },
  {
    slug: 'treasurer-job-description',
    title: 'Treasurer Job Description — Kington Parishes',
    description: "What the Treasurer role involves at St Mary's, Kington — day to day and across the year.",
    // Reachable from the blog post announcing the vacancy, not from the
    // primary nav — same pattern as Donate/Parish News Archive.
    active: null,
    header: true,
  },
  {
    slug: 'life-events',
    title: 'Life Events — Kington Parishes',
    description: 'Baptisms, weddings, funerals and remembrance services across the Kington Parishes.',
    active: 'life-events.html',
    header: true,
  },
  {
    slug: 'get-involved',
    title: 'Get Involved — Kington Parishes',
    description: 'Hire the Parish Hall, join the church fete, support our fundraising, and find out what drives our mission.',
    active: 'get-involved.html',
    header: true,
  },
  {
    slug: 'resources',
    title: 'Resources — Kington Parishes',
    description: 'Books, prayer, and courses to help you explore or grow in the Christian faith — recommended by Kington Parishes.',
    active: 'resources.html',
    header: true,
  },
  {
    slug: 'donate',
    title: 'Donate — Kington Parishes',
    description: 'Choose which of our five churches to support via the Parish Giving Scheme.',
    // Reachable via the header's Donate Now button and Get Involved's Give
    // card everywhere — not in the primary nav, same reasoning as
    // Safeguarding/Parish News Archive.
    active: null,
    header: true,
  },
  {
    slug: 'parish-hall',
    title: 'Parish Hall — Kington Parishes',
    description: "Our parish hall, next to St Mary's, Kington, is available for hire — see inside and get in touch to book.",
    active: 'parish-hall.html',
    header: true,
    image: '/img/parish-hall/exterior.webp',
  },
  {
    slug: 'calendar',
    title: 'Calendar — Kington Parishes',
    description: 'Special services, concerts and one-off events across our five churches, month by month.',
    active: 'calendar.html',
    header: true,
  },
  {
    slug: 'contact',
    title: 'Contact — Kington Parishes',
    description: 'Get in touch with Kington Parishes — office, vicar, and hall booking contacts.',
    active: 'contact.html',
    header: true,
  },
  {
    slug: 'safeguarding',
    title: 'Safeguarding — Kington Parishes',
    description: 'Safeguarding contacts and national helplines for Kington Parishes.',
    active: null,
    header: true,
    // The safeguarding page doesn't need to link to itself.
    safeguardStrip: false,
  },
  {
    slug: 'updates',
    title: 'Site Updates — Kington Parishes',
    description: 'Internal build changelog for this site — not linked from anywhere on the site.',
    active: null,
    header: true,
    // Not pastoral content — skip the safeguard-strip banner, same
    // reasoning as the 404 page.
    safeguardStrip: false,
    robots: 'noindex, nofollow',
  },
  // Hidden how-it-works guide for non-technical members of the website
  // team, explaining (in plain English) how changes reach the live site via
  // Claude/Git/GitHub, and how to set a laptop up to make one. Same pattern
  // as `updates` above: not in NAV/FOOTER_NAV, not pastoral content (no
  // safeguard-strip banner), and noindex/nofollow since it's internal
  // process documentation, not something a site visitor should search their
  // way into. Three pages, all prefixed `help-` and cross-linked from the
  // `help` hub, since this site's build only supports flat `/slug.html`
  // URLs rather than a real `/help/...` subdirectory.
  {
    slug: 'help',
    title: 'Help — How This Website Gets Updated — Kington Parishes',
    description: 'A plain-English guide for the website team: how changes reach the live site, and how to set up a laptop to make one.',
    active: null,
    header: true,
    safeguardStrip: false,
    robots: 'noindex, nofollow',
  },
  {
    slug: 'help-getting-set-up',
    title: 'Setting Up Your Laptop — Help — Kington Parishes',
    description: 'How to install Claude Desktop, create a GitHub account, and paste one block of instructions that gets Claude to set everything else up for you.',
    active: null,
    header: true,
    safeguardStrip: false,
    robots: 'noindex, nofollow',
  },
  {
    slug: 'help-making-a-change',
    title: 'Making a Change — Help — Kington Parishes',
    description: 'What happens, step by step, when you ask Claude to update this website — plus answers to the questions people usually ask first.',
    active: null,
    header: true,
    safeguardStrip: false,
    robots: 'noindex, nofollow',
  },
  // More technical than the other three help- pages, deliberately — for
  // anyone who wants the real infrastructure detail (Cloudflare Workers
  // hosting/DNS, MailerLite, API security, the GitHub repo itself) rather
  // than the plain-English framing the rest of the guide sticks to.
  {
    slug: 'help-technical-details',
    title: 'Technical Details — Help — Kington Parishes',
    description: 'Hosting on Cloudflare Workers, DNS, the templated build that keeps the site DRY, what gets tested before a change goes live, the MailerLite-powered newsletter, how the API is secured, and where the source code lives.',
    active: null,
    header: true,
    safeguardStrip: false,
    robots: 'noindex, nofollow',
  },
  // A deeper-still dive off Technical details' DNS section — the domain's
  // actual DNS records (A/MX/TXT), what each non-A one is for, and that
  // email is on a separate provider (123 Reg/GoDaddy) from the website
  // (Cloudflare). Content is drawn from a real, live public DNS lookup
  // (see git log for this page's own addition) rather than invented, since
  // DNS records are public and verifiable but do drift over time — the page
  // says so and gives the date it was checked.
  {
    slug: 'help-dns-setup',
    title: 'DNS Setup — Help — Kington Parishes',
    description: "A closer look at kingtonparishes.org.uk's DNS records: the A records pointing at Cloudflare, the MX records handing email to 123 Reg/GoDaddy, and what the SPF/DMARC/verification TXT records are for.",
    active: null,
    header: true,
    safeguardStrip: false,
    robots: 'noindex, nofollow',
  },
  {
    slug: 'help-when-it-goes-wrong',
    title: 'When It Goes Wrong — Help — Kington Parishes',
    description: 'What to do if a change looks wrong: ask Claude, revert it, or fail forward — plus why nothing is ever permanently broken.',
    active: null,
    header: true,
    safeguardStrip: false,
    robots: 'noindex, nofollow',
  },
  {
    slug: '404',
    title: 'Page not found — Kington Parishes',
    description: "This page couldn't be found. Find your way back to Kington Parishes' home page.",
    active: null,
    header: false,
    // Footer stays (build number, mediawright credit, contact details) —
    // only the header nav and safeguard-strip banner are dropped, since
    // this page isn't a nav destination.
    safeguardStrip: false,
    canonical: false,
    robots: 'noindex, nofollow',
  },
];
